services:
  app:
    image: itacademy/airports:1.0
    build: .
    ports:
      - "80:8080"
    networks:
      - test
  db:
    image: itacademy/postgres:1.0
    build: postgres
    volumes:
      - "D:/test:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4712vs5988gh
    networks:
      - test
networks:
  test:
    name: test